### ISSUE TITLE
Version 1.0.1 cannot compile on Elixir 1.10

### ISSUE THREAD

**Issue by MatteoJoliveau** [pappersverk/inky#35]
Hello! I'm trying to use this library in an Elixir 1.10 project, and referencing version 1.0.1 from Hex yields the following error:

```
== Compilation error in file lib/display/display.ex ==
** (CompileError) lib/display/display.ex:17: type t/0 undefined (no such type in Inky.Display)
    (elixir 1.10.2) lib/kernel/typespec.ex:898: Kernel.Typespec.compile_error/2
    (elixir 1.10.2) lib/kernel/typespec.ex:937: Kernel.Typespec.fn_args/6
    (elixir 1.10.2) lib/kernel/typespec.ex:377: Kernel.Typespec.translate_spec/8
    (stdlib 3.9.2) lists.erl:1354: :lists.mapfoldl/3
    (elixir 1.10.2) lib/kernel/typespec.ex:229: Kernel.Typespec.translate_typespecs_for_module/2
    (elixir 1.10.2) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
could not compile dependency :inky, "mix compile" failed. You can recompile this dependency with "mix deps.compile inky", update it with "mix deps.update inky" or clean it with "mix deps.clean inky"
```

I see this has been fixed on master thanks to #34, can I ask you to release 1.0.2 on Hex with this fix?
Thank you for the library, it's awesome otherwise!

**Comment by lawik** [comment]
Thanks for the heads up. I won’t be able to do it right away. But I’ll try to get it done shortly.
Until then you should be able to reference the repo on github directly which might serve you well until then.

We’ve just recently had a baby, so moments on the computer are few but I hope to get this done soonish.

**Comment by MatteoJoliveau** [comment]
Congratulations! I totally understand and wish you and your family lots of happiness :D

I'm doing exactly that at the moment, referencing the GitHub master branch in my dependencies. I'll keep an eye on new releases. Thanks!

**Comment by lawik** [comment]
Fixed with the new version 1.0.2. Thanks for letting me know.
